apiVersion: v1
kind: Secret
metadata:
  name: postgres-credential
  namespace: infra
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password # In production, inject this via a vault/pipeline
  POSTGRES_DB: micro_kotlin
