apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credential
  namespace: infra
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: user
  RABBITMQ_DEFAULT_PASS: password # In production, inject this via a vault/pipeline
