apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ui
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-ui
  template:
    metadata:
      labels:
        app: app-ui
    spec:
      containers:
        - name: app-ui
          image: app-ui
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: app-ui
  namespace: apps
spec:
  ports:
    - port: 80
      targetPort: 5173
  selector:
    app: app-ui