apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: micro-kotlin-user
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: kong
username: micro-kotlin-user
credentials:
  - kong-jwt-credential