apiVersion: v1
kind: Secret
metadata:
  name: kong-jwt-credential
  namespace: apps
  labels:
    # Links this secret to the consumer defined below
    konghq.com/consumer: micro-kotlin-user
type: Opaque
stringData:
  # "key" corresponds to the 'iss' (issuer) claim in the JWT,
  # or it can be a generic ID if you don't check claims.
  kongCredType: jwt
  key: "micro-kotlin-issuer"
  algorithm: "HS256"
  # THIS MUST MATCH YOUR SPRING BOOT APPLICATION.YAML SECRET
  secret: "a-string-secret-at-least-256-bits-long"
